name: advance project

on:
  workflow_dispatch

jobs:
  first-jobs-building:
  
    runs-on: ubuntu-latest
    concurrency: 
      group: building-groups
      cancel-in-progress: true
    steps:
      - name: creating repo
        uses: actions/checkout@v4

      - name: installing cowsay
        run: sudo apt install cowsay -y

      - name: building cowsay
        run: cowsay -f "i am dragon" >> dragon.txt

      - name: deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dragon.txt file
          path: ./dragon.txt

      - name: waiting
        run: sleep 15

  second-jobs-building:
    
    needs: first-jobs-building
    runs-on: ubuntu-latest
    steps:
         
      - name: waiting
        run: sleep 10
    
  third-jobs-deploy-prod:
    needs: second-jobs-building
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/upload-artifact@v4

      - name: display dragon
        run: cat dragon.txt




