name: third workflow

on:
  workflow_dispatch

jobs:
    deploy-dragon-on-infra-env:
      runs-on: ubuntu-latest
      steps:
          - name: creating local repo
            uses: actions/checkout@v4

          - name: install dragon tool
            run: sudo apt install cowsay -y
    
    deploy-dragon-on-build-env:
      runs-on: ubuntu-latest
      steps:
          - name: building dreagon files
            run: echo "hi i am dragon" >> dragon.txt
            
    deploy-dragon-on-testing-env:
      runs-on: ubuntu-latest
      steps:
          - name: test dreagon files
            run: cat dragon.txt

          - name: check file
            run: ls -ltra
          
      
  
