name: third workflow

on:
  workflow_dispatch

jobs:
    deploy-dragon-on-test-env:
      runs-on: ubuntu-latest
      steps:
          - name: creating local repo
            uses: actions/checkoutv4

          - name: install dragon tool
            run: sudo install cowsay -y

          - name: test dreagon files
            run: cat dragon.txt

          - name: check file
            run: ls -ltra
          
      
  
